#!/bin/sh -xe
#
# Copyright (c) 2014 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

#
# Builds and deploys the stuff to control the lamps in the kitchen corridor.
# On Debian, requires:
#
# apt-get install gcc libusb-dev libx11-dev make x11-xserver-utils xvfb

# Compile

make

# Update udev rules

install -C 99-lirc-lamp.rules /etc/udev/rules.d/

# Update inittab

INITTAB=/etc/inittab
T=tmp-inittab

add()
{
    ID="$1"
    REST="$2"

    grep -q "^$ID:" $INITTAB || echo "$ID:" >> $T
    sed -i "s%^$ID:.*%$ID:$REST%" $T
}

cat $INITTAB > $T

for i in 1 2 3 4 ; do
    add "x$i" "2345:respawn:`pwd`/run-xvfb $i"
done

add "xgp" "2345:respawn:`pwd`/xgetpixel | logger -t xgetpixel"

install -C $T $INITTAB
telinit q

rm -f $T

# Restart daemons

pkill -f "^/usr/bin/Xvfb" || true
pkill -f "^`pwd`/xgetpixel" || true

echo "Done!"
