#!/bin/sh -xe
#
# Copyright (c) 2014 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

#
# Deploys the JIRA bells in Cambridge.
#
# On Debian, requires:
#
#     apt-get install alsa-utils apache2
#
# JIRA is configured with a web hook:
#
#     Name: XC
#     URL: (this web server)
#     Exclude details: no
#     JQL: project = XC
#     Events: Issue Created, Issue Updated

# Give apache access to audio devices

usermod -aG audio www-data

# Update apache configuration

BELLS_DIR=$(cd $(dirname $0) && /bin/pwd)

sed "s%@BELLS_DIR@%$BELLS_DIR%" apache/bells \
    > /etc/apache2/sites-available/bells

a2ensite bells

service apache2 restart

echo "Done!"
